// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "1bc531c2-b2a2-4ec4-802d-448742c5d05c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575537393);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575537513);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575539979);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575537153);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575537033);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575537273);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575537753);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575537633);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 798720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575536339);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7d3e7554-dcd5-440d-a1d3-142af57bbb57}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575532800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575538843337");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575540653337");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575539957760");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575543557760");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001400");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575537003");
user_pref("browser.slowStartup.averageTime", 8524);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575536343961");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "61e50166965046389869970362eb1ee6");
user_pref("extensions.blocklist.lastModified", "Wed, 04 Dec 2019 18:51:07 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575537395);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001400");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"97109c15-4bd6-4cd7-84c0-5913b70af015\",\"screenshots@mozilla.org\":\"f8fd625f-50d4-4793-8920-a9142843382b\",\"webcompat-reporter@mozilla.org\":\"613e5954-f7c8-4cff-b08f-be4f0a8c4512\",\"webcompat@mozilla.org\":\"ee17ccc6-576f-42df-8bf9-69f88bdce9eb\"}");
user_pref("idle.lastDailyNotification", 1575537240);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575537104);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575537100);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575537240);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "eb6df1d1-3e8d-4270-9b26-31d86ecc5391");
user_pref("security.sandbox.plugin.tempDirSuffix", "0487fc85-d9f1-4978-86d3-378f7898eb58");
user_pref("services.blocklist.addons.checked", 1575537127);
user_pref("services.blocklist.gfx.checked", 1575537127);
user_pref("services.blocklist.onecrl.checked", 1575537127);
user_pref("services.blocklist.pinning.checked", 1575537127);
user_pref("services.blocklist.plugins.checked", 1575537127);
user_pref("services.settings.clock_skew_seconds", -46);
user_pref("services.settings.last_update_seconds", 1575537318);
user_pref("services.settings.main.language-dictionaries.last_check", 1575537127);
user_pref("services.settings.main.sites-classification.last_check", 1575537127);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575537240);
user_pref("toolkit.startup.last_success", 1575537002);
user_pref("toolkit.telemetry.cachedClientID", "52151390-cbb2-4494-8002-4bbbf8f9984e");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
